version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: frontend/scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: frontend/application_start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: frontend/start_server.sh
      timeout: 300
      runas: ubuntu