# .github/workflows/backend-lambda-deploy.yml

name: Backend Lambda Deployment

on:
  push:
    branches: [ "main" ]  # Or your deployment branch
    paths:
      - 'backend/**'  # Trigger only on backend code changes

permissions:
  id-token: write
  contents: read

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: YOUR_AWS_REGION

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Zip Lambda Function
        working-directory: backend 
        run: zip function.zip *   # Zip all files in the backend directory
        
      - name: Update Lambda Function Code
        uses: aws-actions/aws-lambda-update-function-code@v1
        with:
          function-name: form
          zip-file: backend/function.zip  # Path to the zip file within the backend folder

